interface IRoom {
  // INFO
  id: string
  name: string
  description: string
  bed_nums: number
  bathroom_nums: number
  activated: boolean
  max_children: number
  max_adult: number
  photos: any
  hotel_id: string
  // VIEW
  bay: boolean
  ocean: boolean
  sea: boolean
  city: boolean
  garden: boolean
  lake: boolean
  mountain: boolean
  river: boolean
  private_balcony: boolean
  // FACILITIES
  air_conditional: boolean
  tivi: boolean
  kitchen: boolean
  private_pool: boolean
  iron: boolean
  sofa: boolean
  desk: boolean
  soundproof: boolean
  towels: boolean
  toiletries: boolean
  fruit: boolean
  shower: boolean
  slippers: boolean
  hairdry: boolean
  bbq: boolean
  wine: boolean
  fryer: boolean
  kitchen_tool: boolean
  room_type_views?: {
    bay: boolean
    ocean: boolean
    sea: boolean
    city: boolean
    garden: boolean
    lake: boolean
    mountain: boolean
    river: boolean
    private_balcony: boolean
  }
  room_type_facility?: {
    air_conditional: boolean
    tivi: boolean
    kitchen: boolean
    private_pool: boolean
    iron: boolean
    sofa: boolean
    desk: boolean
    soundproof: boolean
    towels: boolean
    toiletries: boolean
    fruit: boolean
    shower: boolean
    slippers: boolean
    hairdry: boolean
    bbq: boolean
    wine: boolean
    fryer: boolean
    kitchen_tool: boolean
  }
  // [more: string]: any
}
export { IRoom }
